version: '3.8'
networks:
  test-authentication:
    external: true
volumes:
  krakend:
services:
  krakend:
    image: devopsfaith/krakend:latest
    restart: unless-stopped
    container_name: krakend
    networks:
      - test-authentication
    volumes:
      - ./:/etc/krakend
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - 8080:8080
  node-authn:
    image: "node:16.18.0"
    user: "node"
    container_name: node-authn
    working_dir: /home/node/app
    environment:
      - NODE_ENV:production
    expose:
      - 8081
    volumes:
      - ./node-authn:/home/node/app
    command: bash -c "node index.js"
    networks:
      - test-authentication
    ports:
      - 8081:8081
